Qol changes
gagneurlab/drop pull request #179
Opened 2021-04-01 07:57 UTC by vyepez88

2021-04-01 10:13 UTC, nickhsmith commented
QOL changes are made to improve the ease and user experience. This branch contains changes to allow the following:

- safe overwriting of the local working directory with changes from the source drop directory. This should save some reprocessing time as only modified scripts will be rerun
- allowing multiple genomic reference files. allow for user to designate multiple references or a global reference from the config file and sample annotation table
- added additional checks and error messages
- use changes in the sample annotation to trigger reruns of the aberrantExpression and MAE pipelines. (aberrantSplicing is still in progress)

2021-04-22 15:32 UTC, mumichae requested changes, later dismissed
Great to see that quite a lot of important issues were addressed!

For dealing with genome information, I'd strongly suggest it to be clearly separated from any SampleAnnotation, MonoAllelicExpression etc.
IMO, a separate class would be the best way to address this.

Similarly, a separate class for count parameters will make things a lot easier to read and work with. However, I couldn't really find how these parameters are used. If they are only written for retrospection, I'd refactor, so that the writing the file would be part of a script instead of a function call during config parsing.

For the safe overwriting of files, it seems as though any additional files from the base repository are removed. I'm not quite sure if that's the behaviour we want.

2021-04-22 15:32 UTC, mumichae commented on docs/source/prepare.rst
> +DROP allows that BAM files from RNA-seq from samples belonging to the same `DROP_GROUP`
Please use two back ticks these and other phrases for the code-style formatting. Single back ticks result in cursive font instead.

e.g.
```
``DROP_GROUP``
``genome``
```

2021-04-22 15:32 UTC, mumichae commented on docs/source/prepare.rst
> +must correspond to the one of the BAM file from RNA-seq.
This topic deserves its own title e.g. "Using different genome assemblies"
Additionally, this section could use some proof-reading to minimise _in that case_/_if so_ clauses, as well as shorten the sentences for better understanding

2021-04-22 15:32 UTC, mumichae commented on docs/source/prepare.rst
> +genome assembly (eg ncbi). If so, the assembly of the reference genome fasta file
UCSC and NCBI are not different genome assemblies but rather different sources of data. Both cover the same range of genome assemblies, such as hg19 and hg38.

In DROP these values define different chromosome styles (`chrX` vs `X`).

2021-04-22 15:32 UTC, mumichae commented on docs/source/prepare.rst
> +genome assembly (eg ncbi). If so, the assembly of the reference genome fasta file
This section should be a separate section rather e.g. "Differing Chromosome Styles"

2021-04-22 15:32 UTC, mumichae commented on docs/source/prepare.rst
> +must correspond to the one of the BAM file from RNA-seq.
I would also move this section to somewhere else in the document, however that would affect multiple other parts of the document. I think we should dedicate a separate PR for restructuring the documentation

2021-04-22 15:32 UTC, mumichae commented on drop/cli.py
> +            remove_tree(local_proj / i)
Do we want to remove files that are not in `base_repo`? What would happen to custom scripts that the user created?

2021-04-22 15:32 UTC, mumichae commented on drop/cli.py
> +def copyModuleCode_safe(repoPaths,projectPaths):
Does `copyModuleCode` need to be renamed to `copyModuleCode_safe`? Would avoid renaming, if possible.

2021-04-22 15:32 UTC, mumichae commented on drop/config/DropConfig.py
> +                    module_obj.writeSampleParams(path,params,include,suffix,group_param = group_param)
I'm assuming these are default values for all samples in the sample annotation?
If so, it would be better to create a new class (preferably in a new file) and document all the entries. Each inner dictionary could also  be represented as an object, so that similarities across modules can be generalised in an interface/abstract class. That way, we'd have a clearer way of defining new modules e.g. RNA variant calling.

2021-04-22 15:32 UTC, mumichae commented on drop/config/DropConfig.py
> +            return self.genomeFiles
I would not mix types here. It would be better to just work with dictionaries and not support string entries

2021-04-22 15:32 UTC, mumichae commented on docs/source/prepare.rst
> +genome               character   Full path of a human reference genome fasta file                                                                                         ``/path/to/hg19.fa``
Would be better to fully change to dictionary entries for `genome` and not allow String entries i.e. this line and functionality should be removed

2021-04-22 15:32 UTC, mumichae commented on drop/config/DropConfig.py
> +        return(self.tempSampleParams)
Is this ever used?
It would also become redundant, if we use classes (as described above), so that we create a new instance instead.

2021-04-22 15:32 UTC, mumichae commented on drop/config/DropConfig.py
> +        return fastaFiles
Great to have a legacy check here!

2021-04-22 15:32 UTC, mumichae commented on drop/config/SampleAnnotation.py
> +                del data_types["GENOME"]
Is it necessary to remove this?

2021-04-22 15:32 UTC, mumichae commented on drop/config/SampleAnnotation.py
> +    def subsetSampleAnnotation(self, column, values, subset=None,exact_match=True):
Add description to `exact_match` in docstring below

2021-04-22 15:32 UTC, mumichae commented on drop/config/SampleAnnotation.py
> +    # build a dictionary from the drop group and column. like getImportCounts with skipping options and dict output
Move this statements within the docstring

2021-04-22 15:32 UTC, mumichae commented on drop/config/SampleAnnotation.py
> +                            column="GENOME", group_key="DROP_GROUP",exact_match = True,skip = False):
Add some description for the remaining parameters

Can also just refer to `subsetSampleAnnotation` function, if parameter names are the same for both functions e.g.

```
:param exact_match: parameter for subsetSampleAnnotation
```

2021-04-22 15:32 UTC, mumichae commented on drop/config/SampleAnnotation.py
> +        return genomeDict
Dictionary comprehension

```py
return {
        sample: value for sample in subset[file_type].tolist()
    }
```

would be more readable

2021-04-22 15:32 UTC, mumichae commented on drop/config/SampleAnnotation.py
> +        subset = self.subsetSampleAnnotation(group_key, group, subset,exact_match=exact_match)
Maybe explain what you subset in each statement. Currently, having 2 subsetting operations w/o explanation is somewhat confusing

2021-04-22 15:32 UTC, mumichae commented on drop/config/SampleAnnotation.py
> +        :param value: values to match in the column. Must be an exact match
A more explainable parameter name would be better e.g. "assembly" (or whatever information is stored in the "GENOME" column

2021-04-22 15:32 UTC, mumichae commented on drop/config/SampleAnnotation.py
> +                            column="GENOME", group_key="DROP_GROUP",exact_match = True,skip = False):
Rename `column` to `genome_column` to make clearer what type of information that column is constrained to. Also add info on that in the docstring

2021-04-22 15:32 UTC, mumichae commented on drop/config/SampleAnnotation.py
> +                            column="GENOME", group_key="DROP_GROUP",exact_match = True,skip = False):
This function seems to be pretty important and useful for more than just Monoallelic Expression. I'd suggest to move all the code related to it into a separate class together with any other genome related operations and data structures

2021-04-22 15:32 UTC, mumichae commented on drop/config/submodules/AberrantExpression.py
> +please fix to only have either external count or BAM processing\n")
Nice check! Might be good to have that in a separate function in the future, especially if we plan to add more sanity checks. But maybe not yet.

2021-04-22 15:32 UTC, mumichae commented on drop/config/DropConfig.py
> +    def getGenomeFiles(self):
This function could go into a Genome class together with all other information and operations regarding genome data. E.g. also include `getGenomes`

2021-04-22 15:32 UTC, mumichae commented on drop/config/submodules/MonoallelicExpression.py
> +    def __init__(self, config, sampleAnnotation, processedDataDir, processedResultsDir,genomeFiles):
Instead of `genomeFiles`, you could pass a Genome object, as discussed above.

2021-04-22 15:32 UTC, mumichae commented on drop/config/submodules/MonoallelicExpression.py
> +            logger.error("WARNING: The genome is defined globally in the config, however non-empty values are in the sample annotation table. Using the globally defined path, please consider fixing t
Would move all this code into a function of a separate Genome class, as it's not specific for MAE

2021-04-22 15:32 UTC, mumichae commented on drop/config/submodules/MonoallelicExpression.py
> +            return genomeFiles
Would enforce the use of dictionary. Makes life easier

2021-04-22 15:32 UTC, mumichae commented on drop/config/submodules/MonoallelicExpression.py
> +but the SA table does not match for sample {sampleID}")
Perfect for a separate Genome class!

2021-04-22 15:32 UTC, mumichae commented on drop/config/submodules/Submodules.py
> +    def update_param_files(self,param_path,filename,sa_df,param_cols,ID,sa_col = "RNA_ID",include = True):
Add a docstring here. Would be good to know what exactly this function does and what for.

Also, I would conform to camel case notation, matching all other methods.

2021-04-22 15:32 UTC, mumichae commented on drop/config/submodules/Submodules.py
> +    def writeSampleParams(self,path,params,include,file_suffix,group_param = False):
Docstring, please

2021-04-22 15:32 UTC, mumichae commented on drop/config/submodules/Submodules.py
> +
Nice handling of default parameters. As suggested before, a separate class for default parameters would be useful. That class would contain these functions and be instantiated in Submodule instances.

2021-04-22 15:32 UTC, mumichae commented on drop/modules/aberrant-expression-pipeline/Counting/countReads.R
> +#'   - input_params: '`sm cfg.getProcessedDataDir() + "/aberrant_expression/{annotation}/params/counts/{sampleID}_countParams.csv" `'
Where is this file used? Is it necessary to specify?

2021-04-22 15:32 UTC, mumichae commented on drop/modules/aberrant-expression-pipeline/Counting/mergeCounts.R
> +#'    - input_params: '`sm cfg.getProcessedDataDir() + "/aberrant_expression/{annotation}/params/merge/{dataset}_mergeParams.csv"`'
Usage?

2021-04-22 15:32 UTC, mumichae commented on drop/modules/aberrant-expression-pipeline/OUTRIDER/results.R
> +#'   - input_params: '`sm cfg.getProcessedDataDir() + "/aberrant_expression/{annotation}/params/results/{dataset}_resultParams.csv"`'
Usage?

2021-04-22 15:32 UTC, mumichae commented on drop/modules/aberrant-splicing-pipeline/FRASER/Summary.R
> +#'                   "/aberrant_splicing/results/{annotation}/fraser/{dataset}/results.tsv"`'
Looks a lot better this way!

2021-04-22 15:32 UTC, mumichae commented on drop/modules/mae-pipeline/MAE/Results.R
> +#'   - input_sample_params: '`sm cfg.getProcessedDataDir() + "/mae/params/results/{dataset}_resultParams.csv" `'
Usage?

2021-04-22 15:32 UTC, mumichae commented on drop/modules/mae-pipeline/Snakefile
> +    output: "{fasta_file_base}.dict"
Where is this variable defined? Why not access if from `cfg` directly?

2021-04-22 15:32 UTC, mumichae commented on drop/modules/mae-pipeline/Snakefile
> +        sample_params = lambda w: cfg.processedDataDir / "mae" / "params/snvs" / (w.rna + "_sampleParams.csv")
Usage?

2021-04-22 15:32 UTC, mumichae commented on drop/template/config.yaml
> +    # the keywords that define the path should be in the GENOME column of the SA table
As mentioned before, using a dictionary should suffice

2021-04-22 15:32 UTC, mumichae commented on drop/utils.py
> +    elif not isinstance(values,str) and exact_match:
Nested conditions might more readable

```py
if exact_match:
    if isinstance(values, str):
        ...
    else:
        ...
else:
     if isinstance(values, str):
        ...
    else:
        ...
```

2021-04-22 15:32 UTC, mumichae commented on tests/pipeline/test_AS.py
> +
Is this still needed/WIP?

2021-04-23 07:22 UTC, mumichae commented on drop/cli.py
> +            remove_tree(local_proj / i)
Please document that DROP autogenerates (pipeline, Analysis scripts) will be overwritten. New files outside of pipeline will not be touched

2021-04-23 07:58 UTC, mumichae commented on drop/config/DropConfig.py
> +            return self.genomeFiles
Please add a docstring

2021-05-04 11:32 UTC, c-mertes approved these changes

2021-05-04 11:38 UTC, merged