Fix dependency graph fails
gagneurlab/drop pull request #200
Opened 2021-05-27 14:03 UTC by mumichae

Dependency graph fails, as soon as any output is printed to standard out beforehand. This pull request filers the rulegraph output, so that prior output doesn't mess up the graph generation.

2021-06-01 21:10 UTC, capricy commented
Could you explain a bit more? It seems like I ran into this issue...

2021-06-02 07:37 UTC, nickhsmith commented
I can explain a bit more. we build dependency graphs which are the images showing the workflow of DROP which can be helpful for following exactly what is happening. We do this using a snakemake command `snakemake --rulegraph` which parses all of the rules and connects the dots about which input and output are required for each process. This gives a text-based version of how the dependency graph will actually look.

```
digraph snakemake_dag {
    graph[bgcolor=white, margin=0];
    node[shape=box, style=rounded, fontname=sans,                 fontsize=10, penwidth=2];
    edge[penwidth=2, color=grey];
	0[label = "all", color = "0.04 0.6 0.85", style="rounded"];
	1[label = "aberrantExpression", color = "0.23 0.6 0.85", style="rounded"];
	2[label = "AberrantExpression_pipeline_Counting_Datasets_R", color = "0.09 0.6 0.85", style="rounded"];
	3[label = "AberrantExpression_pipeline_Counting_Summary_R", color = "0.50 0.6 0.85", style="rounded"];
        ...
        2 -> 1
	11 -> 1
	15 -> 1
         ...
 }
```

which is then interpreted into an image file.

However! If the text file is corrupted with an erroneous print/warning statement (say from Bioconductor having a new version) Or some package printing a warning to STDOUT. The process of interpreting this text file into an image fails, and you have this broken rule.

Our fix for the moment (which we are working on cleaning up) is to use `sed` to parse the text file from the keyword `snakemake dag_file` to the end of the file. Which is in the `dep_graph_fix` branch.

Or if you're committed to avoiding git commands, you can manually do this by editing the following lines. 

NOTE. if you run drop update you will lose these manual changes as they aren't reflected in your base-drop installation. And if you use git, you will need to run `drop update` to transfer the changes from the base installation into your local directory


line 35: Scripts/AberrantExpression/pipeline/Snakefile 
line 31: Scripts/AberrantSplicing/pipeline/Snakefile
line 39: Scripts/MonoallelicExpression/pipeline/Snakefile

So that before the `dot` command you insert this snippet `sed -n '/digraph snakemake_dag/,$p'`

the AberrantExpression line now looks like this for example:
`shell: "snakemake --nolock --rulegraph {AE_index_output} | sed -n '/digraph snakemake_dag/,$p' | dot -Tsvg -Grankdir=TB > {output}"`

2021-06-02 07:55 UTC, nickhsmith requested changes
I did some digging, and to make it more robust I think we should use this sed command instead.

`sed -ne '/digraph snakemake_dag/,/}/p'`

Instead of the going from the match to the end of the file, it matches from `digraph snakemake_dag` to the first closing curly bracket `}`

This will not match any preceding lines nor anything after the curly bracket. Essentially the same, but I think it's a bit more stable.

2021-06-02 14:59 UTC, nickhsmith approved these changes

2021-06-02 15:00 UTC, nickhsmith approved these changes

2021-06-02 15:00 UTC, merged

2021-06-02 17:10 UTC, capricy commented
I tried both:

shell: "snakemake --nolock --rulegraph {AS_index_output} |sed -ne '/digraph snakemake_dag/,/\}/p'| dot -Tsvg -Grankdir=TB > {output}" 
shell: "snakemake --nolock --rulegraph {AS_index_output} |sed -ne '/digraph snakemake_dag/,/}/p'| dot -Tsvg -Grankdir=TB > {output}" 

None worked. The error messages indicated _Single '}' encountered_ :

<img width="1144" alt="Screen Shot 2021-06-02 at 1 08 48 PM" src="https://user-images.githubusercontent.com/18124356/120523303-be9d5680-c3a3-11eb-9ff7-1d2f586fcb60.png">

2021-06-02 17:38 UTC, nickhsmith commented
Sorry there was a typo on my side try }} as inside the snakemake /Python
shell you need to escape it

On Wed 2. Jun 2021 at 19:10, capricy ***@***.***> wrote:

> I tried both:
>
> shell: "snakemake --nolock --rulegraph {AS_index_output} |sed -ne
> '/digraph snakemake_dag/,/}/p'| dot -Tsvg -Grankdir=TB > {output}"
> shell: "snakemake --nolock --rulegraph {AS_index_output} |sed -ne
> '/digraph snakemake_dag/,/}/p'| dot -Tsvg -Grankdir=TB > {output}"
>
> None worked. The error messages indicated *Single '}' encountered* :
>
> [image: Screen Shot 2021-06-02 at 1 08 48 PM]
> <https://user-images.githubusercontent.com/18124356/120523303-be9d5680-c3a3-11eb-9ff7-1d2f586fcb60.png>
>
> —
> You are receiving this because you modified the open/close state.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/gagneurlab/drop/pull/200#issuecomment-853229499>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABWP747H3N6RSIADNQZUYUDTQZQZDANCNFSM45UMFFGA>
> .
>

2021-06-03 00:56 UTC, capricy commented
dependency graph issue resolved. Thank you very much.

But it looks like sample annotation info is not correctly read. I will create a separate issue for that...