Update to version 1.1.0
gagneurlab/drop pull request #229
Opened 2021-07-15 16:17 UTC by mumichae

* Foolproof snakemake (#216)
* Speedup CI (#218)
* Html table cutoff (#217)
* Separate modules (#209)
* Update docs (#228)

2021-07-16 02:43 UTC, nickhsmith approved these changes, later dismissed
Seems good to me. Should be a useful bump

2021-07-16 20:53 UTC, vyepez88 commented on drop/template/Scripts/html_functions.R
> +# Title     : TODO
remove header?

2021-07-21 06:58 UTC, c-mertes requested changes

2021-07-21 06:58 UTC, c-mertes commented on drop/modules/mae-pipeline/Snakefile
>  rule mae:
I think this could be moved up to the `all` rule by having there if-else statements of what to include. This could ease a lot of code.

2021-07-21 06:58 UTC, c-mertes commented on tests/pipeline/test_AE.py
> +        tmp = run(["snakemake", "--unlock"], demo_dir)
do we need this?

2021-07-21 06:58 UTC, c-mertes commented on tests/pipeline/test_AE.py
> +        tmp = run(["snakemake", "--unlock"], demo_dir)
```suggestion
```

2021-07-21 06:58 UTC, c-mertes commented on tests/pipeline/test_AS.py
> +        tmp = run(["snakemake", "--unlock"], demo_dir)
```suggestion
```

2021-07-21 06:58 UTC, c-mertes commented on tests/pipeline/test_MAE.py
> +        tmp = run(["snakemake", "--unlock"], demo_dir)
```suggestion
```

2021-07-21 06:58 UTC, c-mertes commented on tests/pipeline/test_MAE.py
> +        pipeline_run = run(["snakemake", "aberrantExpression", f"-j{CORES}", "--configfile", "config_MAE_norun.yaml"], demo_dir)
```suggestion
        pipeline_run = run(["snakemake", "mae", f"-j{CORES}", "--configfile", "config_MAE_norun.yaml"], demo_dir)
```

2021-07-21 06:58 UTC, c-mertes commented on tests/pipeline/test_MAE.py
> +        pipeline_run = run(["snakemake", "aberrantExpression", f"-j{CORES}", "--configfile", "config_MAE_norun.yaml"], demo_dir)
The question is why did it does not through an error? We should do a fresh start for everything.

2021-07-21 06:58 UTC, c-mertes commented on tests/pipeline/test_pipeline.py
> +    tmp = run(["snakemake", "--unlock"], demo_dir)
```suggestion
```

2021-07-21 06:58 UTC, c-mertes commented on tests/pipeline/test_pipeline.py
> +    pipeline_run = run(["snakemake",  f"-j{CORES}", "--configfile", "config_norun.yaml"], demo_dir)
Does this test make sense here? Everything should be done anyway. So we should rather turn it around and test first if I can switch on a module and then run it.

2021-07-21 06:58 UTC, c-mertes commented on tests/pipeline/test_pipeline.py
> +    pipeline_run = run(["snakemake",  f"-j{CORES}", "--configfile", "config_norun.yaml"], demo_dir)
Same goes for the other parts.

2021-07-21 07:02 UTC, c-mertes commented on drop/template/Scripts/html_functions.R
> +# Created on: 6/21/21
```suggestion
```

2021-07-21 07:02 UTC, c-mertes commented on drop/template/Scripts/html_functions.R
> +# Title     : TODO
yes

2021-07-21 07:03 UTC, c-mertes commented on drop/template/Scripts/html_functions.R
> +
```suggestion
```

2021-07-21 07:03 UTC, c-mertes commented on drop/template/Scripts/html_functions.R
> +
```suggestion
```

2021-07-21 07:06 UTC, c-mertes approved these changes, later dismissed

2021-07-21 07:08 UTC, c-mertes approved these changes

2021-07-21 10:58 UTC, merged