Merge external splicing counts
gagneurlab/drop pull request #247
Opened 2021-08-12 22:47 UTC by c-mertes

This is the fresh take on the merging of external splicing counts. #169

2022-04-01 12:44 UTC, vyepez88 approved these changes, later dismissed

2022-04-01 12:44 UTC, vyepez88 commented on drop/modules/aberrant-splicing-pipeline/Counting/01_4_countRNA_nonSplitReads_merge.R
> +file.create(snakemake@output$done)
```suggestion
file.create(snakemake@output$done)

```

2022-04-04 12:31 UTC, vyepez88 submitted a review, later dismissed

2022-04-21 10:19 UTC, nickhsmith requested changes

2022-04-21 10:19 UTC, nickhsmith commented on drop/modules/aberrant-splicing-pipeline/Counting/03_filter_expression_FraseR.R
> +fds <- saveFraserDataSet(fds)
if using external counts save a new copy of the fds object
else use a symlink of the fds object 

use the new copy/link in future processing

2022-04-21 10:19 UTC, nickhsmith commented on docs/source/output.rst
> +
follow slack comments

2022-04-21 10:19 UTC, nickhsmith commented on drop/modules/aberrant-expression-pipeline/Counting/filterCounts.R
> +}else{
comment to explain

2022-04-21 10:19 UTC, nickhsmith commented on drop/modules/mae-pipeline/MAE/Results.R
> +# summarize these duplicates by taking the maximum of each column for each ID
clean

2022-04-21 10:21 UTC, c-mertes reviewed
Please adapt the code as discussed.

2022-04-21 10:21 UTC, c-mertes commented on docs/source/output.rst
> +results files. We will use the results of the ``demo`` to explain the files generated.::
```suggestion
results files. We will use the results of the ``demo`` to explain the files generated by the following commands:
```

2022-04-21 10:21 UTC, c-mertes commented on docs/source/output.rst
> +html file
```suggestion
HTML file
```

2022-04-21 10:21 UTC, c-mertes commented on docs/source/output.rst
> +easy to read and interpret html files and output files. This section is dedicated to explaining the relevant
```suggestion
easy to read and interpret HTML files and output files. This section is dedicated to explaining the relevant
```

2022-04-21 10:21 UTC, c-mertes commented on docs/source/output.rst
> +        * split of local vs external sample counts
```suggestion
        * number of local vs external sample
```

2022-04-21 10:21 UTC, c-mertes commented on docs/source/output.rst
> +        * the number of aberrantly expressed gene per sample
```suggestion
        * the number of aberrantly expressed genes per sample
```

2022-04-21 10:21 UTC, c-mertes commented on docs/source/output.rst
> +        * histograms relating to mean count distribution with different conditions
```suggestion
        * histograms showing the mean count distributions based on different conditions
```

2022-04-21 10:21 UTC, c-mertes commented on docs/source/output.rst
> +        * information about the expressed genes within each sample and as a dataset
```suggestion
        * expressed genes within each sample and as a whole in the dataset
```

2022-04-21 10:21 UTC, c-mertes commented on docs/source/output.rst
> +        * how batch correction is done and the resulting lack of batch effects
```suggestion
        * correlation between samples before and after the autoencoder correction
```

2022-04-21 10:21 UTC, c-mertes commented on docs/source/output.rst
> +                * this tsv file contains only the significant genes and samples that meet the cutoffs defined in the ``config.yaml`` for ``padjCutoff`` and ``zScoreCutoff``
```suggestion
* Files (for each aberrant expression group)
    * OUTRIDER data files (RDS)
        * You can follow the `OUTRIDER vignette for further individual analysis <https://www.bioconductor.org/packages/devel/bioc/vignettes/OUTRIDER/inst/doc/OUTRIDER.pdf>`. 
    * results files (TSV)
                * the result file contains only the significant genes and samples that meet the cutoffs defined in the ``config.yaml`` for ``padjCutoff`` and ``zScoreCutoff``
```

2022-04-21 10:21 UTC, c-mertes commented on docs/source/output.rst
> +        * comparison of local and external log mean counts
```suggestion
        * comparison of local and external mean counts
```

2022-04-21 10:21 UTC, c-mertes commented on drop/demo/config_relative.yaml
>      - v29
Do we need to maintain it twice the file? In the code base and in the resource tar file?

2022-04-21 10:21 UTC, c-mertes commented on drop/demo/sample_annotation_relative.tsv
> +RNA_ID	RNA_BAM_FILE	DNA_VCF_FILE	DNA_ID	DROP_GROUP	PAIRED_END	COUNT_MODE	COUNT_OVERLAPS	STRAND	HPO_TERMS	GENE_COUNTS_FILE	GENE_ANNOTATION	GENOME	SPLICE_COUNTS_DIR
Same as above, do we need to maintain it twice?

2022-04-21 10:21 UTC, c-mertes commented on drop/modules/aberrant-splicing-pipeline/Counting/01_1_countRNA_splitReads_samplewise.R
> +#'   - workingDir: '`sm cfg.getProcessedDataDir() + "/aberrant_splicing/datasets/fromBam"`'
use ..../datasets/raw-local-{dataset} raw-{dataset} {dataset}

2022-04-22 14:26 UTC, nickhsmith submitted a review, later dismissed

2022-04-22 14:52 UTC, nickhsmith commented on drop/demo/config_relative.yaml
>      - v29
it's not in the resource tar

2022-04-22 15:19 UTC, nickhsmith approved these changes

2022-04-22 16:35 UTC, merged